# Generated by Django 5.2.8 on 2025-11-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(default='ml', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
