# Generated by Django 5.2.8 on 2025-11-20 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_type', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('symptoms_score', models.IntegerField(blank=True, null=True)),
                ('progress_summary', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('consent_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='therapy.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='SessionInventoryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField()),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='user_sessions.therapysession')),
            ],
        ),
    ]
