# Generated by Django 5.2.8 on 2025-11-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pat_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
