# Generated by Django 5.2.8 on 2025-11-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_therapist_therapy_therapistappointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='therapistappointment',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
